# Generated by Django 3.0.2 on 2024-03-02 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_works', '0002_auto_20240302_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberworks',
            name='sortno',
        ),
        migrations.AddField(
            model_name='memberworks',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
