# Generated by Django 3.0.2 on 2024-03-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_works', '0004_auto_20240303_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberworks',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='members_work/files'),
        ),
        migrations.AlterField(
            model_name='memberworks',
            name='link',
            field=models.CharField(blank=True, default='', max_length=2100),
        ),
    ]
