# Generated by Django 3.0.2 on 2024-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_works', '0005_auto_20240303_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberworks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='members_work/files'),
        ),
        migrations.AlterField(
            model_name='memberworks',
            name='link',
            field=models.CharField(blank=True, max_length=2100, null=True),
        ),
    ]
