# Generated by Django 3.0.2 on 2024-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aikotoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aikotoba', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
