# Generated by Django 3.0.2 on 2024-02-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240222_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='delete_flag',
            new_name='is_delete',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
